from tinydb import TinyDB, Query
db = TinyDB('db.jason')
studierende = db.table('Studierende')
klausuren = db.table('Klausuren')
aufsicht = db.table('Aufsicht')
klausurteilnahme = db.table('Klausurteilnahme')

def insert():
    studierende.insert({'Matrikelnummer': '678454', 'Nachname': 'Traudl', 'Vorname': 'Svenja'})
    studierende.insert({'Matrikelnummer': '846584', 'Nachname': 'Sabrina', 'Vorname': 'Trudi'})
    studierende.insert({'Matrikelnummer': '793458', 'Nachname': 'Christa', 'Vorname': 'Christa'})
    studierende.insert({'Matrikelnummer': '767894', 'Nachname': 'Heribert', 'Vorname': 'Eric'})
    studierende.insert({'Matrikelnummer': '876384', 'Nachname': 'Bertram', 'Vorname': 'Eberhard'})
    studierende.insert({'Matrikelnummer': '563984', 'Nachname': 'Laurenz', 'Vorname': 'Heinrich'})
    klausuren.insert({'Klausurid': 1, 'Klausurname': 'Aktuelle Fragestellungen des Information Management', 'Raum': 'G202', 'Dozent': 'Prof. Dr. Theodor', 'Datum': '27.01.2023', 'Zeitraum': '09:00 - 11:00 Uhr', 'Dauer': 120, 'Aufsicht': 'admin', 'Hilfsmittel': 'Keine'})
    klausuren.insert({'Klausurid': 2, 'Klausurname': 'Recht der Informationstechnologie & IT-Sicherheit', 'Raum': 'A216.1', 'Dozent': 'Dipl.-Ing Werner & Prof. Dr. Rodolf', 'Datum': '31.01.2023', 'Zeitraum': '09:00 - 11:00 Uhr', 'Dauer': 120, 'Aufsicht': 'admin', 'Hilfsmittel': 'Gesetzestexte mit Markierungen'})
    klausuren.insert({'Klausurid': 3, 'Klausurname': 'Asset-Management', 'Raum': 'H002', 'Dozent': 'Prof. Dr. Gerfried', 'Datum': '14.01.2023','Zeitraum': '12:00 - 14:00 Uhr', 'Dauer': 120, 'Aufsicht': 'admin', 'Hilfsmittel': 'Keine'})
    klausuren.insert({'Klausurid': 4, 'Klausurname': 'Modellierung Betrieblicher Leistungsprozesse', 'Raum': 'A214',  'Dozent': 'Prof. Dr. Lies', 'Datum': '15.01.2023', 'Zeitraum': '14:00 - 16:00 Uhr', 'Dauer': 120, 'Aufsicht': 'admin2', 'Hilfsmittel': 'Nicht programmierbarer Taschenrechner'})
    klausuren.insert({'Klausurid': 5, 'Klausurname': 'Mathe 1', 'Raum': 'A223',  'Dozent': 'Prof. Dr.-Ing. Karl', 'Datum': '09.01.2023', 'Zeitraum': '10:00 - 12:00 Uhr', 'Dauer': 120, 'Aufsicht': 'admin2', 'Hilfsmittel': 'Formelsammlung; nicht programmierbarer Taschenrechner'})
    klausuren.insert({'Klausurid': 6, 'Klausurname': 'IT-Architektur', 'Raum': 'G225', 'Dozent': 'Prof. Dr. Staab & Prof. Dr. Hildebert', 'Datum': '24.12.1998', 'Zeitraum': '14:00 - 15:30 Uhr', 'Dauer': 90, 'Aufsicht': 'admin2', 'Hilfsmittel': 'Keine'})
    klausuren.insert({'Klausurid': 7, 'Klausurname': 'Datenbanken', 'Raum': 'Westpfalzhalle', 'Dozent': 'Prof. Dr. Artur', 'Datum': '13.07.2020', 'Zeitraum': '15:00 - 17:00 Uhr', 'Dauer': 120, 'Aufsicht': 'admin2', 'Hilfsmittel': 'Keine'})
    klausuren.insert({'Klausurid': 8, 'Klausurname': 'BWL', 'Raum': 'A216.1', 'Dozent': 'Prof. Dr. Josefine', 'Datum': '02.03.2023', 'Zeitraum': '09:00 - 12:00 Uhr', 'Dauer': 180, 'Aufsicht': 'admin2', 'Hilfsmittel': 'Keine'})
    aufsicht.insert({'Aufsichtid': 1, 'Nachname': 'Admin', 'Vorname': 'Admin', 'Benutzername': 'admin', 'Passwort': "admin"})
    aufsicht.insert({'Aufsichtid': 2, 'Nachname': 'Mustermann', 'Vorname': 'Max', 'Benutzername': 'admin2', 'Passwort': "admin2"})
    klausurteilnahme.insert({'Klausurid': 1, 'Matrikelnummer': '767894', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 2, 'Matrikelnummer': '767894', 'Teilnahme': False})
    #klausurteilnahme.insert({'Klausurid': 3, 'Matrikelnummer': '767894', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 4, 'Matrikelnummer': '767894', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 5, 'Matrikelnummer': '767894', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 6, 'Matrikelnummer': '767894', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 7, 'Matrikelnummer': '767894', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 1, 'Matrikelnummer': '846584', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 2, 'Matrikelnummer': '846584', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 4, 'Matrikelnummer': '846584', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 5, 'Matrikelnummer': '846584', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 6, 'Matrikelnummer': '846584', 'Teilnahme': False})
    klausurteilnahme.insert({'Klausurid': 6, 'Matrikelnummer': '678454', 'Teilnahme': False})

db.drop_tables()
insert()

